spring:
  application:
    name: muaring

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        # ??? camelCase ? DB snake_case ?? ??
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  base-url: ${BASE_URL:http://localhost:8080}

  jwt:
    secret: ${JWT_SECRET}
    issuer: muaring
    access-ttl-seconds: 3600  # 1시간
    refresh-ttl-seconds: 604800  # 7일

  image:
    default-profile:
      s3-key: public/default-profile-image.png
      file-name: default-profile-image.png
      file-type: image/png
      file-size: 32768


kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  token-uri: "https://kauth.kakao.com/oauth/token"
  user-info-uri: "https://kapi.kakao.com/v2/user/me"
  scope: "account_email"

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}
  redirect-uri: ${SPOTIFY_REDIRECT_URI}
  token-uri: https://accounts.spotify.com/api/token
  user-info-uri: https://api.spotify.com/v1/me
  scope: user-read-email

cloud:
  aws:
    region: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET_NAME}
      presign:
        upload-exp-minutes: 10
        download-exp-minutes: 5
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY}
        secret-key: ${AWS_S3_SECRET_KEY}

file:
  policy:
    max-size: 5242880  # 5MB (byte 단위)
    max-name-length: 255
    allowed-types:
      - image/jpeg
      - image/jpg
      - image/png

logging:
  level:
    org.springframework.security: DEBUG